language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost1.55-all-dev
script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../ && make test
